### ISSUE TITLE
Gerätename als Objekt anlegen

### ISSUE THREAD

**Issue by halloamt** [halloamt/ioBroker.frontier_silicon#4]
Auch Luxus im Moment, aber wenn man in der Config neben der URL auch noch einen individuellen Namen zur Nutzung in der Objekteliste einbauen könnte, würde es bei mehr als einer Installation die Übersicht in der Liste steigern 🙂

**Comment by halloamt** [comment]
Wurde schon von Anfang an gemacht, bald wird er änderbar.

**Comment by Berchemer** [comment]
> Wurde schon von Anfang an gemacht, bald wird er änderbar.

Das Änderbar wäre sehr schön :-) Danke für die Arbeit...

**Comment by halloamt** [comment]
Ist gemacht und auch schon hochgeladen :)

**Comment by halloamt** [comment]
P.S.: device.friendlyName speichert den Namen. Der wird dann auch in Undok ngezeigt.
